version: "3.6"

services:
  rar:
    container_name: rar
    image: asoltys/raretoshi
    platforms:
      - linux/arm/v7
    ports:
      - "3004:3000"
    restart: always

  lapp:
    depends_on:
      - hasura
      - hbp
      - redis
    container_name: lapp
    image: gcr.io/coinos-326717/github.com/tokenocean/raretoshi-server:prod
    platforms:
      - linux/arm/v7
    restart: always
    command: ["pnpm", "dev"]
    environment:
      # Environment variables...
    tmpfs:
      - /tmp
    volumes:
      - ./app:/app
      - ./custom:/opt/src/hasura/app/custom
      - ${STORAGE_DIR}:/export
    ports:
      - "8091:8091"

  postgres:
    container_name: postgres
    image: postgres:12
    platforms:
      - linux/arm/v7
    restart: always
    environment:
      # Environment variables...
    volumes:
      - ${DATA_DIR}:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  hasura:
    container_name: hasura
    image: hasura/graphql-engine:v2.0.9.cli-migrations-v3
    platforms:
      - linux/arm/v7
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: always
    volumes:
      - ./migrations:/hasura-migrations
      - ./metadata:/hasura-metadata
    environment:
      # Environment variables...

  hbp:
    container_name: hbp
    image: nhost/hasura-backend-plus:v2.4.0
    platforms:
      - linux/arm/v7
    depends_on:
      - hasura
    ports:
      - "3400:3000"
    environment:
      # Environment variables...
    volumes:
      - ./app:/app/custom
    restart: always

  ipfs:
    container_name: ipfs
    image: ipfs/go-ipfs:v0.14.0
    platforms:
      - linux/arm/v7
    ports:
      - 8081:8080
      - 4001:4001
      - 5001:5001
    volumes:
      - ${IPFS_DATA}:/data/ipfs
      - ${STORAGE_DIR}:/export
    restart: always

  liquid:
    container_name: liquid
    image: ghcr.io/vulpemventures/elements:0.21.0.2
    platforms:
      - linux/arm/v7
    volumes:
      - ./liquidregtest/liquid-config/:/home/elements/.elements
    restart: always

  redis:
    container_name: redis
    image: redis
    platforms:
      - linux/arm/v7
    volumes:
      - ./redis:/data
    restart: always

networks: 
  default: 
    name: net
    external: true
